language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"
 
 
install:
  - python setup.py install
  - pip install coveralls

script:
  - python test_runner.py makemigrations
  - python test_runner.py migrate
  - python test_runner.py test
  - coverage run --source=payu test_runner.py  test


after_success:
  coveralls